TRUNCATE TABLE DEV_EXP_TGT.EPAT.HLTHPROFFYACTPLANAGRWMODSV;\

INSERT INTO DEV_EXP_TGT.EPAT.HLTHPROFFYACTPLANAGRWMODSV SELECT  * ,'0' AS EXP_CHK_SUM_NUMBER from DEV_EXP_STG.EPAT.HLTHPROFFYACTPLANAGRWMODSV_STG ;\

